name: Deploy to Streamlit Cloud

on:
  push:
    branches:
      - main  # デプロイをトリガーするブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 使用するPythonのバージョン

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Streamlit Cloud
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Streamlit Cloudにデプロイするためのスクリプトをここに追加
          # 現在、Streamlit Cloudは直接的なAPIデプロイをサポートしていません
          # 代替案として、Secretsをリポジトリのコードに組み込む必要がありますが、セキュリティ上推奨されません
          echo "Streamlit Cloudへの自動デプロイはサポートされていません。"
          echo "手動でStreamlit CloudのSecretsにAPIキーを設定してください。"
